from django.db import models

class RegistroCovid(models.Model):
    fecha_actualizacion = models.DateField()
    id_registro = models.CharField(max_length=50)
    origen = models.IntegerField()
    sector = models.IntegerField()
    entidad_um = models.CharField(max_length=3)
    sexo = models.IntegerField()
    entidad_nac = models.CharField(max_length=3)
    entidad_res = models.CharField(max_length=3)
    municipio_res = models.CharField(max_length=5)
    tipo_paciente = models.IntegerField()
    fecha_ingreso = models.DateField()
    fecha_sintomas = models.DateField()
    fecha_def = models.CharField(max_length=10)  # Puede ser '9999-99-99'
    intubado = models.IntegerField()
    neumonia = models.IntegerField()
    edad = models.IntegerField()
    nacionalidad = models.IntegerField()
    embarazo = models.IntegerField()
    habla_lengua_indig = models.IntegerField()
    indigena = models.IntegerField()
    diabetes = models.IntegerField()
    epoc = models.IntegerField()
    asma = models.IntegerField()
    inmu_supr = models.IntegerField()
    hipertension = models.IntegerField()
    otra_com = models.IntegerField()
    cardiovascular = models.IntegerField()
    obesidad = models.IntegerField()
    renal_cronica = models.IntegerField()
    tabaquismo = models.IntegerField()
    otro_caso = models.IntegerField()
    toma_muestra_lab = models.IntegerField()
    resultado_pcr = models.IntegerField()
    resultado_pcr_coinfeccion = models.IntegerField()
    toma_muestra_antigeno = models.IntegerField()
    resultado_antigeno = models.IntegerField()
    clasificacion_final_covid = models.IntegerField()
    clasificacion_final_flu = models.IntegerField()
    migrante = models.IntegerField()
    pais_nacionalidad = models.CharField(max_length=100)
    pais_origen = models.CharField(max_length=100)
    uci = models.IntegerField()

    def __str__(self):
        return self.id_registro
